/* global chrome */

var l = document.location.href.toString();

var page = l.split("/");
var Page = "";
if (page.length > 3) {
    Page = page[3];
}
var server = "https://dev0055.nullstack.cc/ebay/ebay/fetch.php?usr=";
var ftitle = "https://dev0055.nullstack.cc/ebayEx/find.php?title=";
var fupc = "https://dev0055.nullstack.cc/ebayEx/upc.php?title=";
const Id = chrome.i18n.getMessage("@@extension_id");
const path = "chrome-extension://" + Id + "/";
var flag = path + "res/flags16.png";

var verowords = [
    '(a.r.m.s.)',
    '21 day fix',
    '3 sprouts',
    '3skull',
    '4knines',
    '4life',
    '66fit',
    '66fit limited',
    'a b mckinley',
    'a.r.m.s.',
    'ab lounge',
    'ab marketers',
    'abercrombie & fitch',
    'acc u rate',
    'adafruit',
    'addicore',
    'adeept',
    'admincosmetics',
    'adobe',
    'adonit',
    'adonit creative inc',
    'adonit creative inc.',
    'adonit replacement discs',
    'adt llc',
    'aergun',
    'aftershokz',
    'aiphone',
    'aircraft technical book company',
    'ak47',
    'akg',
    'alaska airlines',
    'alex and ani',
    'alex and ani, llc',
    'alex perez',
    'alfred dunhill',
    'allergan, inc. (botox)',
    'allsaints',
    'alm productions',
    'alpine',
    'altura photo',
    'american educational products',
    'american school of needlework',
    'american scope',
    'american weigh',
    'american weigh scales',
    'american welding society',
    'amiclub',
    'ammex',
    'ammogarand',
    'amscope',
    'amway',
    'amy carinn',
    'amzdeal',
    'anolon',
    'antennax',
    'apex tool group',
    'ar-15',
    'ar15',
    'arc\'teryx',
    'arcsoft',
    'arm\'s reach',
    'as seen on tv',
    'ashleigh talbot',
    'assault',
    'assault rifle',
    'audio advisor, inc.',
    'audio-technica',
    'audioquest',
    'auntie anne\'s',
    'austin city limits',
    'australian gold',
    'author',
    'autism speaks',
    'autodata',
    'autoline products',
    'avery',
    'aviator',
    'avon anew rejuvenate day revitalizing cream',
    'ayayasky',
    'baby bandana drool',
    'babybotte',
    'babybullet',
    'bahco',
    'bananagrams',
    'bandelettes',
    'basilica botanica',
    'baume & mercier',
    'beachbody',
    'beachbody, llc',
    'beadaholique',
    'beamnova',
    'bear armz tactical',
    'beauty junkees',
    'bed head',
    'beelink',
    'belkin',
    'bella fascini',
    'bellabe',
    'benchmade',
    'benova',
    'berenguer dolls',
    'best',
    'best selling',
    'bh cosmetics, inc.',
    'big mouth',
    'bigmouth',
    'bigmouth inc',
    'bill lawrence',
    'bill owen',
    'billie w. taylor',
    'bio clean',
    'bkr¨',
    'blankie tails',
    'blazebox',
    'blazekey',
    'blender bottle',
    'blenderbottle',
    'bliss kiss',
    'bloomberg l.p.',
    'blowgun',
    'bluedot trading',
    'bob',
    'boba',
    'bobjgear',
    'body beast',
    'body sculpture',
    'bodylastics',
    'bongoties',
    'bonjour',
    'bonnie plants',
    'boppy',
    'boruit',
    'bose',
    'bottle breacher',
    'bowers & wilkins',
    'bowers and wilkins',
    'bowflex',
    'braven',
    'break ventures',
    'brenda franklin',
    'breville',
    'brian smith',
    'brightech',
    'britax',
    'britax usa',
    'britaxusa',
    'british phonographic industry',
    'broadway basketeers',
    'brochette',
    'browning laboratories',
    'bruce lee',
    'bua',
    'bubblebagdude',
    'bubby babies',
    'bugaboo',
    'bumbleride',
    'burberry',
    'bushcraft essentials',
    'bushnell',
    'busy life',
    'bvlgari',
    'by msr',
    'by torero inflatables',
    'by leatherman',
    'by mountain buggy',
    'cabeau',
    'cable matters',
    'cablewholesale',
    'caboki',
    'cake boss',
    'caliber corporation',
    'california home goods',
    'calutech',
    'camco',
    'cameraquest',
    'cameraquest.',
    'canadian standards association',
    'canadian standards association and pierre d. landry',
    'candycrate',
    'candyshell',
    'canon',
    'canyon dancer',
    'canyon group',
    'capital brands',
    'capital brands / magic bullet',
    'capitalbrands',
    'cards against humanity',
    'cards against humanity llc.',
    'carl\'s place llc',
    'carlashes',
    'carmick',
    'carolina herrera',
    'cartier',
    'casablanca',
    'caseology',
    'caseology®',
    'casio',
    'catalyst case',
    'cb',
    'cb 72 blank',
    'cbs interactive',
    'cecilio',
    'cellucor',
    'cengage',
    'chanel',
    'channel network audio/video surround receiver with bluetooth and wi-fi',
    'chaz dean studio',
    'chicago iron',
    'chicco',
    'chicwrap',
    'chief architect',
    'chloe',
    'chloe & olive',
    'chrysler',
    'circulon',
    'citikitty',
    'citizen',
    'clairecloud',
    'clairecloud inc.',
    'clarisonic',
    'clayful creations becky',
    'clipsandfastenersinc',
    'coach',
    'cobra',
    'cobra electronics',
    'colart',
    'coldwater creek',
    'columbia',
    'conair',
    'confidence fitness',
    'continental enterprises',
    'cooking savior',
    'copper pearl',
    'copperpearl',
    'cosmic debris',
    'cosmic debris etc. inc.',
    'costechusa',
    'coursesmart',
    'coway',
    'cowboy artists of america',
    'cozy sack',
    'craftsman',
    'cramer',
    'creatology',
    'crest',
    'cricut',
    'criswell embroidery & design',
    'criswell embroidery & design sampler cd',
    'crocs',
    'cruise tags luggage',
    'crutcheze',
    'cryso-jad',
    'crystal allies gallery',
    'cuddle baby',
    'cushcins',
    'cutco',
    'd&m holdings - denon us',
    'd-click',
    'daiwa',
    'dakin',
    'daniel wellington',
    'danielwellington',
    'dansko',
    'darice',
    'dark horse comics',
    'david barton',
    'david delamare',
    'deep cleansing oil',
    'dell',
    'delonghi',
    'delta air lines, inc.',
    'demograss',
    'demograss plus',
    'denon',
    'depo',
    'dermalogica',
    'dermawand',
    'designer skin',
    'dewalt',
    'dhc',
    'diageng',
    'digital goja',
    'dihla',
    'directpremiumbuys',
    'dkst',
    'dmbdynamics',
    'dms',
    'dms international',
    'dna',
    'dnp',
    'dr. denese',
    'dreamline',
    'dreamwear nasal mask',
    'drill brush',
    'drive medical',
    'dropcatch',
    'dropcrate',
    'dt moto',
    'dtx international',
    'dudu-osun',
    'dupont',
    'dupont advion',
    'eames office',
    'earthpan',
    'easton',
    'eccotemp systems',
    'eco zoom stove',
    'ecosmart',
    'ecosphere',
    'edgar rice burroughs',
    'edison nation',
    'electro-harmonix',
    'elgy kitchen',
    'elixir / torbeck industries, llc',
    'elsevier',
    'emjoi',
    'emson',
    'enerlites',
    'enerwave',
    'enfamil',
    'enmotion',
    'epar',
    'epionce',
    'epiphone',
    'epson',
    'epson deutschland gmbh',
    'epsonâ®',
    'ergo baby carrier, inc',
    'ergobaby',
    'escort',
    'esr',
    'esr case',
    'esumic',
    'etienne aigner',
    'eva medical',
    'evelots',
    'excelmark',
    'excelvan',
    'excelvan®',
    'exel',
    'exel international',
    'explodingkittensllc',
    'farberware',
    'farmland',
    'faswin',
    'fat gripz',
    'fba king inc',
    'fender',
    'fenf',
    'fenf,llc',
    'fields of the nephilim',
    'filemaker, inc.',
    'fishman',
    'fitbit',
    'fitueyes',
    'five-star hotel mattress exceptionalsheets',
    'flex belt',
    'focus on college success',
    'foodvacbags',
    'for homegear',
    'ford motor company',
    'foreveryang',
    'formufit',
    'forum novelties',
    'forza',
    'fosbrooke, inc. dba tuft & needle',
    'fossil',
    'frito lay',
    'frux home and yard',
    'fujifilm',
    'fujikam',
    'fujikura',
    'fulvio bianconi',
    'furminator',
    'furminator inc. - united pet group',
    'fédération internationale de football association',
    'g40',
    'gaiam',
    'game room guys',
    'gardex',
    'ge',
    'gear tie',
    'gearo',
    'gefu',
    'general electric',
    'genuine stromberg 97',
    'georgia-pacific',
    'gerber',
    'gerber graduates',
    'gibson',
    'global markets direct',
    'glofx',
    'glovies',
    'gn netcom',
    'go pro camera - woodman labs',
    'goal zero',
    'goddess garden',
    'goja, llc',
    'golden gate grinders',
    'golf outlets usa inc',
    'goobang doo master',
    'gopro',
    'gourmesso',
    'gourmet fruit and nut gift tray',
    'gozbit',
    'gratiae',
    'griffin technology',
    'griffin technology, inc',
    'grill beast',
    'grill floss',
    'grillaholics',
    'grilldoc',
    'grillfloss',
    'grimmspeed',
    'grizzly',
    'grover',
    'grover pro',
    'grover pro percussion, inc.',
    'guess',
    'guess marciano',
    'gummee glove',
    'gummy bear mold',
    'guthy-renker',
    'h2m',
    'h2no',
    'hairburst',
    'hairfinity',
    'hairy r\'s',
    'hang ups',
    'hangerworld limited',
    'hans&alice',
    'harman international industries, inc. (akg acoustics)',
    'harvil',
    'hatchbox',
    'hatchery',
    'hausbell',
    'haynes and boone',
    'hedley',
    'heirloom finds',
    'helga isager',
    'henckels',
    'henry ware holland',
    'higear design',
    'higher education publishers',
    'hipa',
    'hit zone',
    'hks',
    'home brew ohio',
    'homeplanetgear',
    'hoop for select brother machines',
    'hoover',
    'hoover commercial',
    'horizon hobdistributors, inc. horizon',
    'hot buckles',
    'hot tools',
    'hoverboard',
    'howard elliott',
    'howard elliott collection',
    'hp',
    'human touch®',
    'hunter fan company',
    'hydro mousse',
    'hyundai',
    'i-unik',
    'ibenzer',
    'icd research',
    'idiva',
    'ifixit',
    'ill rock merch',
    'illumibowl',
    'image',
    'inc. browning laboratories',
    'inc. ulead systems',
    'infinity jars',
    'ink and toner',
    'innovo',
    'instanatural',
    'instyler',
    'integrity collection',
    'intenze',
    'intenze tattoo ink',
    'international publishers association',
    'intervideo',
    'intuit',
    'iorange-e',
    'iottie',
    'iptvking',
    'iqair',
    'irobot',
    'isotonix',
    'isotonix opc-3',
    'it works',
    'j l brands y722',
    'jabra',
    'jackets 4 bikes',
    'jax classics',
    'jaybird llc',
    'jbl',
    'jdmastar',
    'jeannine holper',
    'jemella ltd.',
    'jempire',
    'jet performance',
    'jim pace',
    'jlab',
    'jo condrill',
    'jo condrill and bennie bough ph.d.',
    'john deere',
    'john wiley',
    'jollylife',
    'jones & bartlett learning',
    'jrm chemical inc',
    'just artifacts',
    'justin bua',
    'k. denise muth',
    'kalos',
    'karla akins',
    'kasho',
    'kef',
    'kekh',
    'kess inhouse',
    'kettle',
    'kevin terry',
    'kevin terry and predestined',
    'keysmart',
    'kidkraft',
    'kimberly-carr home designs',
    'kinetic sand',
    'king baby',
    'king technologies',
    'king technology',
    'kitchen ezentials',
    'kitchen thing-a-ma-jigs',
    'kitchenero',
    'kleinn air horns',
    'kleinn automotive',
    'kleinn automotive air horns',
    'klipsch',
    'klipsch group',
    'kryptonite',
    'kwiksafety',
    'l\'oreal',
    'lamaze',
    'land rover',
    'langley productions',
    'lawn mower cover',
    'leatherman',
    'leebotree',
    'legendary whitetails',
    'lego juris',
    'lets cook',
    'lg',
    'lg electronics',
    'lgelectronics',
    'lgelectronics,inc.',
    'lia sophia',
    'lia sophia and elena kiam',
    'lia sophia and geri berg',
    'lifeproof',
    'lifetrons',
    'lifetrons for people on the move',
    'lightinthebox',
    'lihao',
    'lilian fache',
    'linksys',
    'lip-ink®',
    'lipsy',
    'little trees',
    'live animal trap',
    'liz claiborne',
    'lock pick',
    'lock tools',
    'locksmith',
    'longchamp',
    'luma',
    'luminence, llc',
    'lunchbots',
    'luvvitt',
    'lynda.com',
    'm16',
    'macmillan education',
    'mad about organics',
    'mad dogg athletics',
    'magic bullet',
    'magic hue',
    'magicfiber',
    'magnetic poetry',
    'malva belle',
    'mamiya',
    'manchester united',
    'mannatech',
    'marantz',
    'marpac',
    'matt groening',
    'mcdavid',
    'mcdavid inc.',
    'mcgraw-hill',
    'mcgraw-hill higher education',
    'mcgregor',
    'mcklein',
    'meal prep haven',
    'meal prep haven stackable',
    'mealprephaven',
    'meaningful beauty',
    'medcosouth',
    'megafood',
    'melaleuca',
    'melissa & doug',
    'melodysusie',
    'melondipity',
    'metropolitan lighting',
    'metropolitan tea',
    'michael josh',
    'microsoft',
    'microsoft corporation',
    'mifanstech',
    'mightymaxbattery',
    'mike barrett',
    'minecraft',
    'minelab',
    'minelab electronics',
    'mitchell repair information company',
    'moen',
    'moichef',
    'mooneyes',
    'moonrays',
    'mountain buggy',
    'mountain khakis',
    'mpd digital',
    'mpowerd',
    'msr',
    'mts / uk home and garden store ltd',
    'my pillow',
    'my recovers',
    'mypillow',
    'mypillow inc',
    'mypillow, inc',
    'myprotein',
    'mystudygroup101 llc',
    'nailstar',
    'nandita singh',
    'nato',
    'natural dog company',
    'naturo sciences',
    'naturosciences',
    'nautilus, inc',
    'neet cables',
    'neetcables',
    'neewer',
    'neocutis',
    'neocutis bio-restorative day cream',
    'neova',
    'nest',
    'netpicks',
    'neutrik',
    'neutrik ag',
    'new era',
    'new sunshine',
    'nialaya',
    'nicer dicer',
    'nike',
    'ninja',
    'nintendo',
    'nissan',
    'nite ize',
    'noble house',
    'noble house home furnishings',
    'nordic naturals',
    'nordstrom',
    'nu skin',
    'nuskin/ pharmanex',
    'nutrabolt',
    'nutri bullet',
    'nutrilite',
    'nuvo',
    'nvid',
    'oasisplus',
    'obagi',
    'oculus',
    'oki data',
    'olay',
    'omiera',
    'omiera labs',
    'omiera labs - omar rx, inc.',
    'online fabric store',
    'onramp technologies',
    'ontel products',
    'open university',
    'opi',
    'oreck',
    'oreck commercial',
    'oreckcommercial',
    'oribe',
    'oribe hair care, llc',
    'originalbedband',
    'osmosis',
    'otterbox',
    'oxgord',
    'oxo',
    'oxo good grips',
    'oxo products',
    'packit',
    'packrats collectibles',
    'paco rabanne',
    'palm springs',
    'panasonic',
    'panda wireless',
    'panda wireless inc',
    'panor',
    'pantry elements',
    'paolo soleri',
    'parts express',
    'patu cable ties',
    'paula deen',
    'paw patrol',
    'pawspamper',
    'pearson education',
    'peleg',
    'penchant',
    'penson & co',
    'perfect crush',
    'peri-k',
    'perkinknives',
    'pestbye',
    'petsafe',
    'pevonia',
    'phiten',
    'photomedex',
    'picking',
    'pipetto',
    'planet pegasus llc',
    'plantronics',
    'platypus',
    'playboy enterprises',
    'playmonster',
    'playtex',
    'plush lined desk eyeglass',
    'pmd personal microderm',
    'pocket hose',
    'pokemon go game tips, cheats, plus, download guide unofficial',
    'polk audio',
    'polybubble',
    'popsockets',
    'pourfect',
    'powernet',
    'powerstep',
    'pratico',
    'praticokitchen',
    'pratipad',
    'pravda,inc',
    'premier',
    'pro g-flyer party toy',
    'proactiv',
    'procella',
    'pronto moda',
    'prostar deals',
    'protégé beauty',
    'pugster',
    'pugsterjewelry',
    'puig',
    'punk and pissed',
    'pura d\'or',
    'puracy',
    'purdey\'s',
    'purneat',
    'qm-h',
    'qs',
    'qsc',
    'que acoustics',
    'quickfillballoons',
    'quiksilver',
    'r.s.v.p.',
    'rabbito',
    'rachael ray',
    'rachel caine',
    'radiancy',
    'radio systems corporation',
    'razormaid',
    'rdk products',
    'real flame',
    'real techniques starter',
    'rean',
    'rean a brand of neutrik ag',
    'red',
    'red bull',
    'red steagall',
    'refurbished',
    'rembrandt charms',
    'resmed',
    'restoration hardware',
    'revol trading inc',
    'revolver drill brush',
    'rick higgins',
    'ridgerock tools',
    'riorand',
    'riorandtvbox',
    'rockin\' paws',
    'rodan + fields',
    'rogeliobueno',
    'roku',
    'rolbak',
    'roleff',
    'ropri',
    'rosetta stone',
    'rowena cherry',
    'rsvp',
    'rsvp international',
    'rubiks',
    'ruffoni',
    'ruki home',
    'rx 4 hair loss',
    's\'well',
    'sado-nation',
    'sally caldwell fisher and chalk & vermilion fine arts',
    'sandvik',
    'santas christmas town',
    'sanyo',
    'scaredy cut',
    'seemecnc',
    'segway inc',
    'seisco international limited',
    'self balancing',
    'selk\'bag',
    'sena',
    'sephra',
    'serious steel assisted pull-up bands',
    'serious steel fitness',
    'shaderz',
    'sharkskinzz',
    'sheer strength labs',
    'shenzhen',
    'shop247 usa',
    'shop247.com',
    'shure',
    'sigma',
    'sigma beauty',
    'silalive',
    'silver lined snow globe',
    'silverstone',
    'simien',
    'simplehuman',
    'sivan health',
    'skiboards.com',
    'skinmedica',
    'skip hop',
    'skip,hop,zoo',
    'skullcandy',
    'skycaddie',
    'skystreamx',
    'slendertone',
    'sloggers',
    'smarterfresh',
    'smartsound software',
    'smartwool',
    'smith & wesson',
    'snap-on',
    'snap-on official licensed product',
    'snappower',
    'society6',
    'solar water pumping kit',
    'solid strategic',
    'solta medical',
    'songmics',
    'songmics-clothes rack',
    'songmics-jewelry box',
    'songmics-jewelry stand',
    'songmics-laptop desk',
    'songmics-laundry organizer',
    'songmics-makeup case',
    'songmics-shoe rack',
    'songmics-shoe tree',
    'songmics-storage ottoman',
    'songmics-watch box',
    'sony',
    'sound basics',
    'soundbasics',
    'soundcast',
    'spark and bee',
    'speakstick',
    'speck',
    'speck products',
    'spigen',
    'spigen sgp co., ltd',
    'spin master, ltd',
    'spinido',
    'spoonk',
    'sportdog',
    'sports hoop',
    'sports tek',
    'spyder',
    'squatty potty',
    'stable step',
    'star kids',
    'star shower',
    'star shower motion',
    'starshower',
    'statue of liberty replica',
    'stephen shore',
    'stewart golf',
    'stewartgolf',
    'stl international',
    'studio banana things',
    'stuff2color',
    'stussy',
    'stx international',
    'summer escapes skimmer',
    'sunny health',
    'sunny health & fitness',
    'supco',
    'super power supply llc',
    'supereze',
    'supernight',
    'supreme gear',
    'survival shovel',
    'swagway',
    'swarovski',
    'swiss army brand',
    'symantec',
    't-cobbler',
    't-shirt bordello',
    'tactacam',
    'tamiya',
    'tasco',
    'taser international',
    'tasiglobal',
    'techsmith',
    'tecscan',
    'tedbaker',
    'teeter',
    'teeter hang ups',
    'teeter hangups',
    'tekbotic',
    'telebrands',
    'telescopic rake',
    'tens machine',
    'thane',
    'thane international',
    'thane international, inc',
    'the annenberg foundation trust at sunnylands',
    'the association of american publishers',
    'the cat personal safety',
    'the joy factory',
    'the modern gummy',
    'the red society',
    'theravent max',
    'thule',
    'tiffany & co.',
    'tom kelley',
    'tomei',
    'tommie',
    'tommie copper',
    'tommy hilfiger',
    'tomy',
    'top greener',
    'topgreener',
    'toppik',
    'torero',
    'torero inflatables',
    'torro',
    'total gym',
    'tottenham hotspur f.c.',
    'tpdc service',
    'traeger',
    'training mask',
    'travelrest',
    'traxxas 6852x',
    'trollbeads',
    'trophy',
    'true image',
    'trx',
    'trx essentials strength',
    'tti floor care north america',
    'tubshroom',
    'tuft & needle',
    'turbotech',
    'tyc',
    'ugg',
    'ugg australia',
    'ugs corp.',
    'ulead',
    'ulead systems',
    'uncommon laundry',
    'under armour',
    'united scope',
    'urepair',
    'useless box',
    'uspicy',
    'vampire squid cards',
    'van cleef & arpels',
    'vanguard',
    'varylala',
    'velcro',
    'velvet skin coat',
    'vendibelle',
    'vera bradley',
    'versace',
    'versaliving llc',
    'versipack',
    'vickie milazzo',
    'victorio',
    'vigilant',
    'vigilantpersonalprotectionsystems',
    'vinousq',
    'viper',
    'visalus',
    'visalus vi-shape',
    'vivitar',
    'vivre cosmetiques',
    'vogue professional',
    'voltseasy',
    'vonhaus',
    'vortex',
    'vortex optics',
    'waba fun',
    'wacom',
    'wahoo',
    'walker edison',
    'walkydog',
    'warner home video',
    'waterpik',
    'wd music',
    'weathertech',
    'web brands',
    'weber',
    'weider',
    'wemo',
    'wen® chaz dean',
    'werfamily',
    'wise foods',
    'wobbleworks',
    'woodstock amazing grace chime',
    'world by shotglass',
    'woss trainer',
    'wuppessen inc.',
    'wwe',
    'x-mini',
    'x-tronic',
    'xbats',
    'y beauty junkees',
    'y&t',
    'ya',
    'yalokin',
    'yeti',
    'ykl world',
    'yklworld',
    'yogitoes',
    'yonanas',
    'yopo',
    'young living',
    'young\'s inc',
    'yuosoar',
    'yvonne hedley',
    'zenoplige',
    'zephyr',
    'zepp',
    'zerosweat',
    'ziggyboard',
    'zildjian',
    'zippyusa',
    'zodiac',
    'zoe+ruth',
    'zully polycarbonate',
    'zumba',
    'zumba fitness',
    'zvue',
    'zwilling j.a. henckels',
    'zyliss'
];

var riskywords = [
    'CleanSpa',
    'PopSocket',
    'Nickelodeon',
    'Zizo',
    'Brondell',
    'Spigen',
    'Lego',
    'Disney',
    'PS4',
    'Otterbox',
    'Hefty',
    'Skechers',
    'Casio',
    'Boss',
    'Polaroid',
    'Philips',
    'Garmin',
    'Motorola',
    'Apple',
    'iphone',
    'fitbit',
    'lg',
    'samsung',
    'Creatine',
    'galaxy',
    'ipad',
    'pixel',
    'google',
    'Poison',
    'health',
    'first aid',
    'xmas',
    'xbox',
    'x box',
    'ps 4',
    'playstation',
    'sony',
    'money',
    'Treatment',
    'Luminara',
    'Lighter',
    'Skin Care',
    'Mask',
    'gopro',
    'dji',
    'oil',
    'omega',
    'PAW Patrol',
    'Tactical',
    'Sex',
    'Food',
    'Medicine',
    'Shampoo',
    'Weapon',
    'Capsule',
    'Pepper Spray',
    'Diet',
    'Trademark',
    'Patent',
    'Gold jewlery',
    'NFL',
    'Perfume',
    'tatoo',
    'Marvel',
    'NBA',
    'NCAA',
    'NHL',
    'Flea',
    'filter',
    'knife',
    'drug',
    'weed',
    'alcohol',
    'amazon',
    'batman',
    'superman',
    'dvd',
    'movie',
    'airpod',
    'blue parrot',
    'christmas',
    'Pokemon',
    'Fujifilm',
    'Rubiks',
    'jenga',
    'Costume',
    'cream',
    'fake money',
    'pieces',
    'piece',
    'pcs',
    'pc',
    'set',
    'feet',
    'foot',
    'ft',
    'mm',
    'cm',
    'mg',
    'oz',
    'qt',
    'ounces',
    'ounce',
    'kit',
    'packs',
    'pack',
    'pk',
    'lb',
    'lbs',
    'kg',
    'counts',
    'count',
    'inch',
    'inches',
    '"',
    'gallon',
    'pound',
    'pounds',
    'quart',
    'quarts',
    'pair',
    'pairs',
    'liter',
    'liters',
    'size',
    'king',
    'queen',
    'tray',
    'twin',
    'gun',
    'axe',
    'amazon.com',
    'sold',
    'free shipping',
    '1"',
    '2"',
    '3"',
    '4"',
    '5"',
    '6"',
    '7"',
    '8"',
    '9"',
    'camco',
    'Beats',
    'wwe',
    'wwf',
    'Playstation4',
    'Pills',
    'Enhancement',
    'Natural',
    'Shape',
    'PLAYMOBIL',
    'Vacuum Massage',
    'free',
    'ship',
    'Oakley',
    'Cellulean',
    'Chocolate',
    'Snack',
    'ZonePerfect',
    'Formula',
    'Dee Cee',
    'Tablets',
    'NETGEAR',
    'TP-Link',
    'Moto 360',
    'Conditioner',
    'Algaefix',
    'DEWALT',
    'Anal',
    'Blood',
    'test',
    'Clear Eyes',
    'Erotic',
    'Dragon Ball Z',
    'Hasbro',
    'Vitamins',
    'Vitamin',
    'replacement',
    'diamond',
    'Jewelry',
    'Luxury',
    'Watch',
    'Adult',
    'Vibrating',
    'MEDICAL',
    'California',
    'Window',
    'Angularizer',
    'Sim',
    'Android',
    'Iwatch',
    'Gpx',
    'Inc',
    'Rifle',
    'Assult',
    'Fast Draw',
    'Shotgun',
    'Battle',
    'toshiba',
    'dell',
    'hp',
    'KitchenAid',
    'zippo',
    'Chemical',
    'Certified Refurbished',
    'Certified',
    'Refurbished',
    'National Geographic',
    'National',
    'Geographic',
    'Kitchen Aid',
    'Fisher Price',
    'Hunting',
    'pandora',
    'Capsules',
    'Burners',
    'Calories',
    'Stun Gun',
    'Sterling Silver',
    'Nautica',
    'Gold Plated',
    'Mavic',
    'Spark',
    'ammo',
    'Roku',
    'Panasonic',
    'K Cup',
    'YETI',
    'anker',
    'Gillette',
    'Chemo',
    'SYMA',
    'SanDisk',
    'Samsonite',
    'Weight Loss',
    'Tattoo',
    'PopSockets',
    'Microsoft',
    'Waterpik',
    'one',
    'two',
    'three',
    'Four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten',
    'Eleven',
    'Twelve',
    'twenty',
    'thirty',
    'forty',
    'fifty',
    'Sixty',
    'seventy',
    'ninety',
    'hundred',
    'Thousand',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '100',
    '1000'
];
var CONFIG = null;
function checkVero(title) {
    var yy = title.toLowerCase().split(" ");
    var r = {};
    for (var x = 0; x < verowords.length; x++) {
        for (var y = 0; y < yy.length; y++) {
            if (yy[y].trim() === verowords[x].trim()) {
                console.log("vero on: " + yy[y] + " / word : " + verowords[x]);
                r.vero = true;
                break;
            } else {
                r.vero = false;
            }
        }
        if (r.vero)
            break;
    }

    for (var x = 0; x < riskywords.length; x++) {
        for (var y = 0; y < yy.length; y++) {
            if (yy[y].trim() === riskywords[x].trim()) {
                console.log("risky on: " + yy[y] + " / word : " + riskywords[x]);
                r.risky = true;
                break;
            } else {
                r.risky = false;
            }
        }
        if (r.risky)
            break;
    }
    return r;
}

function startProcess(S, cb) {
    if (typeof cb === "undefined") {
        cb = function () {};
    }
	
    $('.theadforscript').css("display", "inline-block");
    $('.theadforscript').html("Competitors");
    $('.tdforscript').css("display", "inline-block");

    var X = $('#datatable-responsive tr');
    var count = X.length;
    X.each(function (i, F) {
        var f = $(F).find("td:nth-child(2)");
        var id = $(f).attr("data-itemid");
        var title = $(f).attr("data-title");

        var vr = {vero: false, risky: false};
        if (S.vero === "on") {
            if (typeof title !== "undefined") {
                vr = checkVero(title);
                if (vr.risky && vr.chkrisky) {
                    if ($(f).find(".risky").length <= 0) {
                        $(f).find("h4 b").append('<span class="risky"></span>');
                    }
                }
                if (vr.vero) {
                    if ($(f).find(".risky").length <= 0) {
                        $(f).find("h4 b").append('<span class="risky"></span>');
                    }
                }
            }
        }

        $(F).find('.tdforscript').html('<span class="cpcolx" id="cp_' + id + '">...</span>');
        switch (S.check) {
			
            case "title":
                $.get(ftitle + escape(title) + '&id=' + id + '&country=' + S.country, function (D) {
                    if (D.count > 0) {
                        $('#cp_' + D.id).html(D.count).css("color", "#666");
                    } else {
                        $('#cp_' + D.id).html("N/A").css("color", "#57a512");
                    }
                });
                break;
            case "upc":
                $.get(fupc + id + "&id=" + id + '&country=' + S.country, function (D) {
                    if (D.count > 1) {
                        $('#cp_' + D.id).html(D.count).css("color", "#666");
                    } else {
                        $('#cp_' + D.id).html("N/A").css("color", "#57a512");
                    }
                });
                break;
            default:
                console.log("unknown setting: " + S.check);
        }
        if (!--count)
            cb();
    });
}

function waitForLoad(cb) {
    var checker = setInterval(function () {
        if ($('#header').is(":visible")) {
            clearInterval(checker);
            setTimeout(function () {
                cb();
            }, 50);
        }
    }, 100);
}

function reveal() {
    $('.theadforscript').css("display", "inline-block");
    $('.theadforscript').html("Competitors");
    $('.tdforscript').css("display", "inline-block!important");
    $('.tdforscript').each(function (i) {
        $(i).css("display", "inline-block!important");
    });
}

function rebind() {
    $('body .paginate_button').each(function (i, E) {
        $(E).on("click", function () {
            reveal();
            setTimeout(function () {
                reveal();
            }, 5);
            setTimeout(function () {
                startProcess(CONFIG);
            }, 50);
        });
    });
}


function _begin(e) {
    chrome.runtime.sendMessage({method: "getConf"}, function (response) {
        waitForLoad(function () {
            if (e) {
                response.chkrisky = true;
            } else {
                response.chkrisky = false;
            }
            CONFIG = response;
			
            startProcess(response);
            setInterval(function () {
                rebind();
            }, 500);
        });
    });
}

if (l.indexOf("/SearchCompetitor") !== -1) {
	
	if(l.indexOf('Competitor=')>-1){
		
		$('#header').css("display", "none");
        _begin(false);
	}
	else{
    $('.btnGo').on("click", function () {
        $('#header').css("display", "none");
        _begin(false);
    });
    $('.txtSearch').on("keypress", function (e) {
        if (e.which === 13) {
            $('#header').css("display", "none");
            _begin(false);
        }
        if (l.indexOf('Index?s') !== -1) {
            setTimeout(function () {
                $('#header').css("display", "none");
                _begin(false);
            }, 3000);
        }
	});
	
	}
}

if (l.indexOf("/Analyze/Index/") !== -1) {
    $('#datatable-responsive tr').each(function (i, F) {
        var f = $(F).find("td:first");
        $(f).addClass("_zikacon");
        var usr = $(f).find("a em").text().toString().trim();
        var id = "zika-" + i;
        $(f).addClass("_" + id + "c");
        $(f).append('<span class="_zika" id="' + id + '">Loading..</span>');
        $.get(server + usr + "&id=" + id, function (D) {
            var s = document.createElement("span");
            if (typeof D.country_code === "string") {
                $(s).addClass("f16").addClass("flag16-" + D.country_code.toLowerCase()).css("background-image", "url(" + flag + ")");
                $('#' + D.id).html("").append(s).append('&nbsp;<span class="zconm">' + D.country + '</span>');
            }
        });
    });
}

if (l.indexOf("/CategoryResearch/Result") !== -1) {
    $('#datatable-responsive tr').each(function (i, F) {
        var f = $(F).find("td:first");
        $(f).addClass("_zikacon");
        var usr = $(f).find("a").text().toString().trim();
        var id = "zika-" + i;
        $(f).addClass("_" + id + "c");
        $(f).append('<span class="_zika" id="' + id + '">...</span>');
        console.log(id);
        $.get(server + usr + "&id=" + id, function (D) {
            var s = document.createElement("span");
            if (typeof D.country_code === "string") {
                $(s).addClass("f16").addClass("flag16-" + D.country_code.toLowerCase()).css("background-image", "url(" + flag + ")");
                $('#' + D.id).html("").append(s).append('&nbsp;<span class="zconm">' + D.country + '</span>');
            }
        });
    });
}